language: python
sudo: false
jobs:
  include:
    - name: "Python 3.6 on Linux"
      python: '3.6'
      before_install:
        - pip install dnspython
        - pip install python-ldap
install:
  - pip install django
  - pip install codecov
  - pip install pytest-cov
script: coverage run -m pytest django_adtools/tests.py
after_success:
  - codecov