language: python
sudo: false
jobs:
  include:
    - name: "Python 3.6 on Linux"
      python: '3.6'
      before_install:
        - pip install dnspython
        - pip install python-ldap
install:
  # - cat /etc/os-release
  # - dpkg-query -L libldap2-dev | grep lber
  - echo $PATH
  - pip install -r requirements.txt
  - django-admin startproject adtools .
  - echo "INSTALLED_APPS.append('django_adtools')" >> adtools/settings.py
  - python manage.py makemigrations django_adtools
  - python manage.py migrate
  - pip install codecov
  - pip install pytest-cov
  # - docker pull dwimberger/ldap-ad-it
  # - docker run -it --rm -p 10389:10389 dwimberger/ldap-ad-it
script: coverage run manage.py test
after_success:
  - codecov